### ISSUE TITLE
Value of the field in Delivery Api is always null

### ISSUE THREAD

**Issue by Ahmed-Adel3** [vokseverk/Vokseverk.KeyValueEditor#9]
I tried the KeyValue editor and it is working fine but when I try to retrieve the values in the content delivery API, it always returns null in the property value 

Here is the editor in a page
![image](https://github.com/user-attachments/assets/2fa0ea4d-ff88-4584-8795-33444e06266b)

And here is how it reflects in the content delivery Api
![image](https://github.com/user-attachments/assets/707dc93c-ad36-45df-85ca-1a74b12bb7ca)

**Comment by greystate** [comment]
Hey there @Ahmed-Adel3 — thank you for the report 🙌 

I have no idea why this is (I have not yet used the Content Delivery API for anything myself) but I probably need to "support" it in the `PropertyEditorValueConverter`...

If you know what's missing, I would gladly open this up for a Hacktoberfest contribution?

/Chriztian

**Comment by Ahmed-Adel3** [comment]
Hello Chriztian, 
    Please check the open pull request #11  , it should fix the error for the content delivery API.

I'd be glad if this is opened for Hacktoberfest :)

Thanks
